module.exports = {
  name: '1to7',
  alias: ['17', 'guess17', 'one to seven'],
  desc: 'Guess the hidden number from 1 to 7',
  category: 'Games',
  execute: async (sock, m) => {
    await sock.sendHtmlMessage(m.chat, { html: `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:12px;background:linear-gradient(145deg,#101827,#24103a);font-family:Arial;color:#fff}.card{max-width:360px;margin:auto;padding:20px;border-radius:24px;background:#ffffff12;border:1px solid #ffffff2b;text-align:center;box-shadow:0 14px 35px #0007}h1{margin:0 0 8px;color:#ffd166}.sub{opacity:.75}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:22px 0}.grid button{height:54px;border:0;border-radius:14px;background:#6c63ff;color:white;font-size:20px;font-weight:700}.grid button:active{transform:scale(.94)}#status{min-height:28px;font-weight:700}button#reset{width:100%;height:42px;border:1px solid #ffffff44;border-radius:12px;background:#ffffff18;color:#fff}</style></head><body><main class="card"><h1>1 TO 7</h1><div class="sub">Pick a number. Can you read the bot’s mind?</div><div class="grid" id="grid"></div><div id="status">Choose your number</div><p>Score: <b id="score">0</b> · Streak: <b id="streak">0</b></p><button id="reset">NEW ROUND</button></main><script>(()=>{const g=document.getElementById('grid'),s=document.getElementById('status'),sc=document.getElementById('score'),st=document.getElementById('streak'),r=document.getElementById('reset');let score=0,streak=0;function round(){g.innerHTML='';for(let n=1;n<=7;n++){const b=document.createElement('button');b.textContent=n;b.onclick=()=>pick(n);g.appendChild(b)}s.textContent='Choose your number'}function pick(n){const answer=Math.floor(Math.random()*7)+1;if(n===answer){score++;streak++;s.textContent='✓ Correct! The number was '+answer}else{streak=0;s.textContent='✗ Not this time — it was '+answer}sc.textContent=score;st.textContent=streak;[...g.children].forEach(b=>b.disabled=true);setTimeout(round,900)}r.onclick=round;round()})()</script></body></html>` });
  }
};
