services:
  - type: web
    name: cody-whatsapp-bot
    repo: https://github.com/crysnovax/CODY
    branch: main
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm ci --omit=dev
    startCommand: node index.js
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: OWNER_NUMBER
        sync: false
      - key: OWNER_NAME
        sync: false
      - key: BOT_NAME
        sync: false
      - key: SESSION_ID
        sync: false
      - key: PREFIX
        sync: false
