const axios = require('axios');
const { request, downloadImage } = require('../../Plugin/prexzy');
module.exports = { name:'cartoon', alias:['cartoona','toonai'], category:'AI', desc:'Turn a replied image into a cartoon', execute: async (sock,m,{reply}) => {
  const quoted=m.quoted; if(!quoted || !quoted.mtype?.includes('image')) return reply('✘ Reply to an image.');
  try { const input=await quoted.download(); if(!input) return reply('✘ Could not download the image.'); await reply('🎨 Creating cartoon...'); const upload=await axios.post('https://cdn.crysnovax.link/upload',input,{headers:{'Content-Type':'image/jpeg'},timeout:30000}); const imageurl=upload.data?.url||upload.data?.link; if(!imageurl) throw Error('Image upload failed'); const r=await request('/ai/cartoon',{imageurl},{timeout:120000}); const url=r.data?.anime_image; if(!url) throw Error(r.data?.error||'No cartoon image returned'); return sock.sendMessage(m.chat,{image:await downloadImage(url),caption:'🎨 *Cartoon generated by Prexzy AI*'},{quoted:m}); } catch(e){ console.error('[CARTOON]',e.message); return reply('✘ Cartoon generation failed.'); }
}};
